### ISSUE TITLE
No GUI search results

### ISSUE THREAD

**Issue by tristan957** [JosephMart/Flix-with-Friends#6]
Currently the search results are only in the terminal. We need the search results in the GUI. Currently there are no errors in creating the GUI. It's just not being shown. I think it has something to do with the search results stack not being shown.

**Comment by tristan957** [comment]
I think all we need is a list of movies called results.

**Comment by JosephMart** [comment]
List called `results` is now populated with movies that satisfy the search criteria

**Comment by tristan957** [comment]
Poster images are now being shown as of commit: `bb26845aff51d1773a3152e766125e48165dde81`
